### ISSUE TITLE
assumes vagrant plugin-reload exists

### ISSUE THREAD

**Issue by mkinney** [StefanScherer/adfs2#1]
I got this error:

$ vagrant up dc --provider virtualbox
Bringing machine 'dc' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.

To fix:
    vagrant plugin install vagrant-reload

**Comment by StefanScherer** [comment]
Thanks @mkinney. Fixed with https://github.com/StefanScherer/adfs2/commit/1964264fb424853ec292e7f5800c76414bcdce0d
