### ISSUE TITLE
Where can i found "windows_2012_r2"?

### ISSUE THREAD

**Issue by danielmenezesbr** [StefanScherer/adfs2#4]
Where can i found "windows_2012_r2" [1]?

https://github.com/StefanScherer/adfs2/blob/master/Vagrantfile#L6

**Comment by StefanScherer** [comment]
Look at the Vagrant Cloud https://app.vagrantup.com you can discover lots of boxes there.  Then adjust the name of the box in the Vagrantfile. 
Otherwise you can build your own box with Packer. My templates can be found at https://github.com/StefanScherer/packer-windows.

**Comment by StefanScherer** [comment]
When you build a VM with Packer you should also add the sysprep step. When Vagrant boots a VM then every VM generates its own SID which is needed to join a domain.

See https://github.com/clong/DetectionLab/blob/master/Packer/windows_2016.json#L28 for an example or the https://github.com/StefanScherer/packer-windows/blob/my/README-shutdown_command.md
